name: "deployment"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version number"
        required: true
        type: string

jobs:
  deployment_job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.version }}
      - uses: actions-rs/toolchain@v1
        with:
          target: "x86_64-apple-darwin"
          toolchain: stable
          default: true
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target x86_64-apple-darwin
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          artifacts: "target/release/alfred"

          token: ${{ secrets.GITHUB_TOKEN }}

